---

- name: Remove previous docker installation
  apt:
    name: "{{ docker_remove_old_packages }}"
    state: absent

- name: Install prerequisites packages
  apt:
    name: "{{ docker_prerequisites_packages }}"
    state: present

- name: Import Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  
- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: yes

- name: Install Docker CE
  apt:
    name: "{{ docker_install_packages }}"
    state: present
