---

docker_remove_old_packages:
  - docker 
  - docker-engine
  - docker.io
  - containerd
  - runc

docker_prerequisites_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

docker_install_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io