---

harbor_folder: /opt/

harbor_online_installer: "https://github.com/goharbor/harbor/releases/download/v2.0.2/harbor-online-installer-v2.0.2.tgz"


docker_pip_packages:
  - docker
  - docker-compose

